dist: xenial
language: python
matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
before_script:
  - pip install --upgrade pytest
install:
  - pip install .
script: py.test
